# Generated by Django 6.0.4 on 2026-04-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingreport',
            name='contributor',
            field=models.CharField(default='Anonymous Scout', max_length=80),
        ),
        migrations.AddField(
            model_name='scoutingreport',
            name='projected_nba_level',
            field=models.CharField(choices=[('rotation', 'Rotational NBA Player'), ('starter', 'Starting Level Player'), ('all_star', 'All-Star Caliber Player'), ('superstar', 'Superstar Player')], default='starter', max_length=20),
        ),
    ]
