# Generated by Django 6.0.4 on 2026-04-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0002_scoutingreport_contributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutingreport',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
